---
 
 - name: allow 8080 port
   firewalld:
     port: 8080/tcp
     permanent: yes
     state: enabled
   notify: restart firewalld

 - name: apache to listen on 8080
   lineinfile:
     path: /etc/httpd/conf/httpd.conf
     regexp: Listen 80
     line: Listen 8080
   notify: restart apache
